### ISSUE TITLE
Make icon transparent?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/ad-analysis-for-facebook#1]
Spotted today while installing from AMO on Firefox 62.0.3 w/ dark theme.
The corners of the icon seem to be white.

![ad_analysis_for_facebook_ _get_this_extension_for_ _firefox__en-us_](https://user-images.githubusercontent.com/557895/47303903-0c416800-d5da-11e8-880d-822e42a29317.png)

![blank_skitch_document](https://user-images.githubusercontent.com/557895/47303979-398e1600-d5da-11e8-84be-6af6f49151d8.png)

**Comment by jcchuang** [comment]
@pdehaan I've uploaded a new icon with transparent borders. The icon is now showing up correctly everywhere (e.g., on the add-on listing page) _except_ in the dialogue box that you took a screenshot of (i.e., in the drop-down box from the address bar).

Do you know if it just takes a few days for AMO to propagate the image? Or, do I need to explicitly trigger a refresh? If the latter, do you know where/how I can file such a bug? Thanks!

**Comment by jcchuang** [comment]
@pdehaan I bumped the extension version, and that seemed to have triggered a refresh. The new icon is now used in the address bar drop-down box.
